#!/usr/bin/env python3

import glob
import json
import os
import subprocess

from production import interfaces
from production import utils

problems = sorted(glob.glob(os.path.join(utils.get_data_dir(), 'qualifier/problem_*.json')))

exe = os.path.join(utils.get_project_root(), 'production/play_icfp2015')
cmdline = [exe]

for problem in sorted(glob.glob(os.path.join(utils.get_data_dir(), 'qualifier/problem_*.json'))):
  cmdline.append('-f')
  cmdline.append(problem)
for power_phrase in interfaces.POWER_PHRASES:
  cmdline.append('-p')
  cmdline.append(power_phrase)

p = subprocess.Popen(cmdline, bufsize=2**11, stdout=subprocess.PIPE)
out = str(p.stdout.read(), 'UTF-8')

sols = []
tot_score = 0
for sol in json.loads(out):
  sols.append((sol['problemId'], sol['seed'], utils.score_of_solution(sol)))
  tot_score += utils.score_of_solution(sol)

for sol in sorted(sols):
  print('Problem: %-8d     Seed: %-8d     Score: %d' % sol)

print('Total score: %d' % tot_score)
